### PR TITLE
c() function

### PR DESCRIPTION
**Pull request by bozmik**
@al2na @katwre

### CODE REVIEW

**Comment by al2na** [comment]
I'm not sure this is the most efficient way to do this. I think all you have to do is:
```
ScoreMatrixList(append(list(ml),sml@.Data))
```

or
```
ScoreMatrixList(append(sml@.Data,list(ml)))
```

ml is the object to be appended, sml is the ScoreMatrixList object. you can also do, if you have more than one things to append. You can parse that from "..." maybe
```
ScoreMatrixList(append(sml@.Data,list(ml,ml)))
```

**Comment by bozmik** [comment]
@al2na @katwre 
I pushed an improved version of the c() function with using the append(). Look at this new commit: c() with using “append” 

Attached you will find the comparison of the computation time between the previous function (commit 30aa2fa2) and the current c() function (commit 4b9dbb9f). The best is the new c() function. 
[Computation time.pdf](https://github.com/BIMSBbioinfo/genomation/files/1035120/Computation.time.pdf)

**Comment by katwre** [comment]
@bozmik Cool, it looks that's it's faster now! @al2na I think sth like this `ScoreMatrixList(append(list(ml),sml@.Data))` won't work, because output of its argument `data(cage)
data(promoters)
data(cpgi)
sm = ScoreMatrix(target=cage, windows=promoters)
targets = list(cage=cage, cpgi=cpgi)
ml = ScoreMatrixList(targets=targets, windows=promoters, bin.num=50)
append(list(ml),sml@.Data)
` is a list of mix of scorematrixlists and score matrices. When `ScoreMatrixList()` is feeded with such argument it gives an error: `> ScoreMatrixList(append(list(ml),sml@.Data))
Error in ScoreMatrixList(append(list(ml), sml@.Data)) : 
  windows of class GRanges must be defined`). But sth this would work `as(append(ml@.Data,sml@.Data), "ScoreMatrixList")`. So then `ml@.Data` and `sml@.Data` gives a list of score matrices

**Comment by katwre** [comment]
@bozmik Could you update news and bump up the version according to current BioC devel version? I think, right now it's 1.9.1 so the next one is 1.9.2

**Comment by bozmik** [comment]
@katwre  done :)

**Pull request merged**
