### PR TITLE
enrichmentMatrix() function

### PR DESCRIPTION
**Pull request by bozmik**
@al2na, @katwre 
That's my suggestion for solving the issue #138 :)

### CODE REVIEW

**Comment by al2na** [comment]
@frenkiboy could you review this ?

**Comment by katwre** [comment]
I completely forgot to update svn with github Bimsbbionfo master branch (super sorry for that!). There are two small commits in svn that are not in github Bimsbbionfo master (they only bumped up version).

**Comment by katwre** [comment]
@bozmik ok, so basically you wrote an enrichmentMatrix() function that takes as an argument ScoreMatrixControl or ScoreMatrixListControl object. A ScoreMatrixControl function has 2 arguments: a scorematrix object that corresponds to an IP and a scorematrix that corresponds to a control and adequately with ScoreMatrixListControl function, but it takes scorematrixlists as arguments. It's a lot of lines of code that maybe are actually not needed. It would be way easier if you could write a function enrichmentMatrix() that can take either pair of scorematrices and scorematrixlists without using ScoreMatrixControl and ScoreMatrixListControl functions.

Here is an example:
`setGeneric("enrichmentMatrix",
           function(ip,control) 
             standardGeneric("enrichmentMatrix") )
#' @aliases enrichmentMatrix,ScoreMatrix,ScoreMatrix-method
#' @rdname enrichmentMatrix-methods
#' @usage  \\S4method{enrichmentMatrix}{ScoreMatrix,ScoreMatrix}(ip,control)
setMethod("enrichmentMatrix",signature("ScoreMatrix","ScoreMatrix"),
          function(ip, control){
            
            mat = log2( (ip + 1)/(control + 1) )
            return(mat)
          })

library(GenomicRanges)
bam.file <- system.file('unitTests/test.bam', package='genomation')
windows <- GRanges(rep(c(1,2), each=2), IRanges(rep(c(1, 2), times=2), width=5))
IP <- ScoreMatrix(target=bam.file,windows=windows, type='bam')
control <- ScoreMatrix(target=bam.file, windows=windows, type='bam') * 0.002
enrichmentMatrix(IP, control)`

**Comment by bozmik** [comment]
@katwre
I did it in that way because I think in case of using a ScoreMatrixControlList the user might have a higher control over the corresponding IP and control samples. Having two long ScoreMatrixList objects the user has to be sure that the positions on the lists of the corresponding IPs and controls are the same. With ScoreMatrixCotrol the user can place the corresponding IP and control samples in one object and I think less experienced user could feel better having a possibility to check whether the corresponding samples are placed together and the enrichmentMatrix() function computes the enrichment over just this combination. This feature might be useful in case of very long ScoreMatrixControlLists.

**Comment by bozmik** [comment]
@katwre
Of course, if you think that's insignificant feature, I will create the basics version of this function you described :)

**Pull request closed without merging**
