### PR TITLE
Count bam faster in cpp

### PR DESCRIPTION
**Pull request by alexg9010**
Hey Vedran,

I have implemented the fast retrieval of library size in c++ using Samtools idxstats-like code.
Maybe you can integrate this, it will make normalization like 100 times faster :)

### CODE REVIEW

**Comment by al2na** [comment]
Thank you @alexg9010 , good hacking!! changing original idxstats and storing the output in R::data.frame :) @frenkiboy @katwre we should merge this to devel, could you do that? we should update the NEWS as well.

**Comment by katwre** [comment]
merge it to devel or master? Note: our BIMSB master should be equal to BioC svn devel as I good understand.

**Comment by al2na** [comment]
if that's the case master, than we should also remember to bump up the version and add alex as ctb

**Comment by alexg9010** [comment]
I will open again when no check fails

**Comment by al2na** [comment]
please don't forget to merge this whenever you have time

**Pull request merged**
